---
title: "Untitled"
author: "Thanh Bui"
date: "2026-04-15"
output: html_document
---

### Data exploration

```{r eval = T, warning = F, message = F}
library(tidyverse)
library(tigris)
library(broom)
library(dplyr)
library(car)
library(quantreg)
library(corrplot)
library(ggplot2)
library(sf)
```


```{r eval = T, warning = F, message = F}
# 1. PLACES Stroke data
data2 <- read_csv("~/Downloads/PLACES__Local_Data_for_Better_Health,_County_Data_2024_release_20260422.csv") %>%
  filter(MeasureId == "STROKE",
         Data_Value_Type == "Crude prevalence",
         Year == 2022) %>%
  select(
    countyID = LocationID,
    STROKE = Data_Value,
    state = StateAbbr,
    county = LocationName
  ) %>%
  distinct() %>%
  mutate(countyID = as.character(countyID))

# 2. County Health Rankings / analytic data
data11 <- read_csv("~/Downloads/analytic_data2022.csv") %>%
  select(
    countyID = `5-digit FIPS Code`,
    obesity_prev = `Adult obesity raw value`,
    physical_inactive = `Physical inactivity raw value`,
    air_pollution = `Air pollution - particulate matter raw value`,
    diabetes_prev = `Diabetes prevalence raw value`,
    smoke = `Adult smoking raw value` 
  ) %>%
  mutate(countyID = as.character(countyID))

# 3. County boundaries
bound_data <- counties(cb = TRUE, year = 2022, class = "sf") %>%
  select(countyID = GEOID) %>%
  mutate(countyID = as.character(countyID))

# 4. Final merge
data <- bound_data %>%
  left_join(data2, by = "countyID") %>%
  left_join(data11, by = "countyID") %>%
  filter(!is.na(STROKE)) %>%
  select(countyID, state, county, STROKE, 
         smoke, obesity_prev, physical_inactive, 
         air_pollution, diabetes_prev, geometry)

summary(data)
colSums(is.na(data))
```
Drop geometry

```{r}
data <- data %>%
  mutate(
    countyID = as.numeric(countyID),
    smoke = as.numeric(smoke),
    obesity_prev = as.numeric(obesity_prev),
    physical_inactive = as.numeric(physical_inactive),
    air_pollution = as.numeric(air_pollution),
    diabetes_prev = as.numeric(diabetes_prev)
  ) %>% st_drop_geometry() %>%
  na.omit()
nrow(data)
sum(is.na(data$STROKE)) 
sum(is.na(data$smoke))
moments::skewness(data$STROKE) 
```

```{r eval = T, warning = F, message = F}
hist.stroke <- ggplot(data, aes(x = STROKE)) +
  geom_histogram(binwidth = 0.5,    # adjust this as needed
                 fill = "#FFF9C4", 
                 color = "black") +
  labs(title = "Histogram of Stroke Prevalence",
       subtitle = "Skewness = 0.6",
       x = "Stroke Prevalence",
       y = "Frequency") +
  theme_minimal()
hist.stroke
saveRDS(hist.stroke, "hist.stroke.rds")
```

```{r}
library(ggcorrplot)
cor_matrix <- cor(data %>% select(STROKE, smoke, obesity_prev, physical_inactive, 
                    air_pollution, diabetes_prev), use = "complete.obs", method = "pearson")
cor.stroke <- ggcorrplot(cor_matrix, method = "circle", type = "upper", lab = TRUE, lab_size = 2.5, 
                         colors = c("blue", "white", "red"), title = "Correlation Matrix", ggtheme= theme_minimal())

cor.stroke
saveRDS(cor.stroke, "cor.stroke.rds")
```

```{r}
model_vif <- lm(STROKE ~ smoke + diabetes_prev + obesity_prev + physical_inactive, data = data)
summary(model_vif)
vif(model_vif)
```


```{r}
model_vif <- lm(STROKE ~ smoke + diabetes_prev + physical_inactive, data = data)
vif(model_vif)
summary(model_vif)
```

```{r}
plot.dist <- ggplot(data, aes(x = diabetes_prev, y = STROKE)) +
  geom_point(alpha = 0.4, col = "gray50") +
  geom_smooth(method = "lm", se = FALSE, aes(color = "OLS")) +
  geom_quantile(quantiles = c(0.25, 0.5, 0.75, 0.9), aes(color = factor(..quantile..))) +
  scale_color_manual(
    name = "Line Type",
    values = c(
      "OLS" = "red",
      "0.25" = "#1f77b4",
      "0.5"  = "#2ca02c",
      "0.75" = "#ff7f0e",
      "0.9"  = "#9467bd"
    ),
    labels = c(
      "OLS" = "OLS",
      "0.25" = "25th Percentile",
      "0.5"  = "Median",
      "0.75" = "75th Percentile",
      "0.9"  = "90th Percentile"
    )
  ) +
  labs(title = "Distribution of QR vs. OLS on Increasing Percentile",
       x = "X", y = "Y") +
  theme_minimal()


plot.dist
saveRDS(plot.dist, "plot.dist.rds")

```

### Data Modeling



```{r}
ols <- lm(STROKE ~ smoke + diabetes_prev + physical_inactive, 
                data = data)

qr_median <- rq(STROKE ~ smoke + diabetes_prev + physical_inactive, 
                tau = 0.5, data = data)

summary(ols_model)

summary(residuals(qr_median))
summary(qr_median, se = "boot")
```

This table shows a row by row coefficient values of two models.

```{r}
# ols_coefs <- tidy(ols_model) %>%
#   mutate(Model = "OLS", 
#          estimate = round(estimate, 4),
#          std.error = round(std.error, 4))
# 
# qr_coefs <- tidy(qr_median) %>%
#   mutate(Model = "QR Median", 
#          estimate = round(estimate, 4),
#          std.error = round(std.error, 4))
# 
# comparison <- bind_rows(ols_coefs, qr_coefs) %>%
#   select(term, Model, estimate, std.error, p.value = p.value) %>%
#   arrange(term, Model)
# 
# print(comparison)
```


### Coefficient Heterogeneity Plot


```{r}
taus <- c(0.25, 0.5, 0.75, 0.90)

qr_multi <- rq(STROKE ~ smoke + diabetes_prev + physical_inactive, 
               tau = taus, data = data)

coef_table <- tidy(qr_multi, se.type = "nid") %>%
  mutate(
    estimate = round(estimate, 4),
    std.error = round(std.error, 4),
    p.value = round(p.value, 4)
  ) %>%
  filter(term != "(Intercept)") %>%
  select(tau, term, estimate) %>%
  arrange(term, tau)

print(coef_table)
```



```{r}
coef.stroke <- ggplot(coef_table, aes(x = tau, y = estimate, color = term, group = term)) +
  geom_point(size = 3) +
  geom_line() +
  geom_hline(data = tidy(ols_model) %>% filter(term != "(Intercept)"),
             aes(yintercept = estimate, color = term), linetype = "dashed") +
  facet_wrap(~ term, scales = "free_y") +
  labs(title = "Coefficient Heterogeneity Across Quantiles vs OLS (dashed)",
       x = "Percentile", y = "Estimate") +
  theme_minimal()

coef.stroke
saveRDS(coef.stroke, "coef.stroke.rds")
```

### Comparing the Prediction Interval

```{r}
# 50% middle
qr25 <- rq(STROKE ~ smoke + diabetes_prev + physical_inactive, 
                data = data, tau = 0.25)
qr75 <- rq(STROKE ~ smoke + diabetes_prev + physical_inactive, 
                data = data, tau = 0.75)

# 70% middle 
qr15 <- rq(STROKE ~ smoke + diabetes_prev + physical_inactive, 
                data = data, tau = 0.15)
qr85 <- rq(STROKE ~ smoke + diabetes_prev + physical_inactive, 
                data = data, tau = 0.85)

# 80% middle 
qr10 <- rq(STROKE ~ smoke + diabetes_prev + physical_inactive, 
                data = data, tau = 0.1)
qr90 <- rq(STROKE ~ smoke + diabetes_prev + physical_inactive, 
                data = data, tau = 0.9)

# 90% middle
qr05 <- rq(STROKE ~ smoke + diabetes_prev + physical_inactive, 
                data = data, tau = 0.05)
qr95 <- rq(STROKE ~ smoke + diabetes_prev + physical_inactive, 
                data = data, tau = 0.95)
```



```{r}
############# 50 middle
pred.ols50 <- predict(ols, interval = "prediction", level = 0.5)
# get the bound
lower.ols5 <- pred.ols50[, "lwr"]
upper.ols5 <- pred.ols50[, "upr"]
# count
within.ols.50 <- data$STROKE >= lower.ols5 & data$STROKE <= upper.ols5
# qr
pqr25 <- predict(qr25)
pqr75 <- predict(qr75)
within_qr5 <- data$STROKE >= pqr25 & data$STROKE <= pqr75
```

```{r}
############# 70 middle
pred.ols70 <- predict(ols, interval = "prediction", level = 0.7)
# get the bound
lower.ols7 <- pred.ols70[, "lwr"]
upper.ols7 <- pred.ols70[, "upr"]
# count
within.ols.70 <- data$STROKE >= lower.ols7 & data$STROKE <= upper.ols7
# qr
pqr15 <- predict(qr15)
pqr85 <- predict(qr85)
within_qr7 <- data$STROKE >= pqr15 & data$STROKE <= pqr85
```


```{r}
############# 80 middle
pred.ols80 <- predict(ols, interval = "prediction", level = 0.8)
# get the bound
lower.ols8 <- pred.ols80[, "lwr"]
upper.ols8 <- pred.ols80[, "upr"]
# count
within.ols.80 <- data$STROKE >= lower.ols8 & data$STROKE <= upper.ols8
# qr
pqr10 <- predict(qr10)
pqr90 <- predict(qr90)
within_qr8 <- data$STROKE >= pqr10 & data$STROKE <= pqr90
```


```{r}
############# 90 middle
pred.ols90 <- predict(ols, interval = "prediction", level = 0.9)
# get the bound
lower.ols9 <- pred.ols90[, "lwr"]
upper.ols9 <- pred.ols90[, "upr"]
# count
within.ols.90 <- data$STROKE >= lower.ols9 & data$STROKE <= upper.ols9
# qr
pqr05 <- predict(qr05)
pqr95 <- predict(qr95)
within_qr9 <- data$STROKE >= pqr05 & data$STROKE <= pqr95
```


```{r}
library(knitr)
library(dplyr)
pre.interval.stroke <- data.frame(
  "Interval" = c("50%", "70%", "80%", "90%"),
  OLS = round(c(sum(within.ols.50), sum(within.ols.70), sum(within.ols.80), sum(within.ols.90)) / nrow(data) * 100, 2),
  QR = round(c(sum(within_qr5), sum(within_qr7), sum(within_qr8), sum(within_qr9))/nrow(data) * 100, 2)
)

pre.interval.stroket <- pre.interval.stroke %>%
  kable(
    col.names = c("Prediction Interval", "OLS", "QR"),
    align = c("l", "c", "c"),
    digits = 2,
    booktabs = TRUE,
    linesep = ""
  )

print(pre.interval.stroket)

saveRDS(pre.interval.stroket, "pre.interval.stroket.rds")
```

```{r}

# More information about `revealjs`:
# <https://quarto.org/docs/reference/formats/presentations/revealjs.html>
# :::

```

